# Generated by Django 3.1 on 2020-12-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['create_time'], name='create_time_idx'),
        ),
    ]
