# Generated by Django 3.1 on 2021-01-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201215_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['create_time']},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='finish_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
