# Generated by Django 3.1 on 2021-01-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210105_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
