# Generated by Django 3.1 on 2020-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_cross_off',
            field=models.BooleanField(default=False),
        ),
    ]
