# Generated by Django 3.1 on 2020-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_is_cross_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
