# Generated by Django 3.1 on 2020-09-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'In Queue'), (1, 'Running'), (2, 'Finished'), (3, 'Error')], default=0)),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
    ]
