# Generated by Django 3.1 on 2020-09-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawltask',
            options={'ordering': ['-update_time', '-submit_time']},
        ),
    ]
